In [ ]:
# Aproximación ingenua

import pandas as pd  #  type: ignore


df = pd.read_csv(
    "../data/credit_card_approval.csv.zip",
    compression="zip",
)
df.columns = df.columns.str.lower()

df.shape

(9709, 20)

In [2]:
df.head()

,id,gender,own_car,own_property,work_phone,phone,email,unemployed,num_children,num_family,account_length,total_income,age,years_employed,income_type,education_type,family_status,housing_type,occupation_type,target
0,5008804,1,1,1,1,0,0,0,0,2,15,427500.0,32.868574,12.435574,Working,Higher education,Civil marriage,Rented apartment,Other,1
1,5008806,1,1,1,0,0,0,0,0,2,29,112500.0,58.793815,3.104787,Working,Secondary / secondary special,Married,House / apartment,Security staff,0
2,5008808,0,0,1,0,1,1,0,0,1,4,270000.0,52.321403,8.353354,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,Sales staff,0
3,5008812,0,0,1,0,0,0,1,0,1,20,283500.0,61.504343,0.000000,Pensioner,Higher education,Separated,House / apartment,Other,0
4,5008815,1,1,1,1,1,1,0,0,2,5,270000.0,46.193967,2.105450,Working,Higher education,Married,House / apartment,Accountants,0

In [3]:
df.isna().sum()

id                 0
gender             0
own_car            0
own_property       0
work_phone         0
phone              0
email              0
unemployed         0
num_children       0
num_family         0
account_length     0
total_income       0
age                0
years_employed     0
income_type        0
education_type     0
family_status      0
housing_type       0
occupation_type    0
target             0
dtype: int64

In [4]:
df.describe()

,id,gender,own_car,own_property,work_phone,phone,email,unemployed,num_children,num_family,account_length,total_income,age,years_employed,target
count,9.709000e+03,9709.000000,9709.000000,9709.000000,9709.000000,9709.000000,9709.000000,9709.000000,9709.000000,9709.000000,9709.000000,9.709000e+03,9709.000000,9709.000000,9709.000000
mean,5.076105e+06,0.348749,0.367700,0.671542,0.217427,0.287671,0.087548,0.174683,0.422804,2.182614,27.270059,1.812282e+05,43.784093,5.664730,0.132145
std,4.080270e+04,0.476599,0.482204,0.469677,0.412517,0.452700,0.282650,0.379716,0.767019,0.932918,16.648057,9.927731e+04,11.625768,6.342241,0.338666
min,5.008804e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,2.700000e+04,20.504186,0.000000,0.000000
25%,5.036955e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,13.000000,1.125000e+05,34.059563,0.928150,0.000000
50%,5.069449e+06,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,26.000000,1.575000e+05,42.741466,3.761884,0.000000
75%,5.112986e+06,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,3.000000,41.000000,2.250000e+05,53.567151,8.200031,0.000000
max,5.150479e+06,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,19.000000,20.000000,60.000000,1.575000e+06,68.863837,43.020733,1.000000

In [5]:
df.dtypes

id                   int64
gender               int64
own_car              int64
own_property         int64
work_phone           int64
phone                int64
email                int64
unemployed           int64
num_children         int64
num_family           int64
account_length       int64
total_income       float64
age                float64
years_employed     float64
income_type         object
education_type      object
family_status       object
housing_type        object
occupation_type     object
target               int64
dtype: object

In [6]:
from pprint import pprint

for col in df.select_dtypes(include=["object"]).columns:
    print(f"{col}: ", end="")
    pprint(df[col].unique())

income_type: array(['Working', 'Commercial associate', 'Pensioner', 'State servant',
       'Student'], dtype=object)
education_type: array(['Higher education', 'Secondary / secondary special',
       'Incomplete higher', 'Lower secondary', 'Academic degree'],
      dtype=object)
family_status: array(['Civil marriage', 'Married', 'Single / not married', 'Separated',
       'Widow'], dtype=object)
housing_type: array(['Rented apartment', 'House / apartment', 'Municipal apartment',
       'With parents', 'Co-op apartment', 'Office apartment'],
      dtype=object)
occupation_type: array(['Other', 'Security staff', 'Sales staff', 'Accountants',
       'Laborers', 'Managers', 'Drivers', 'Core staff',
       'High skill tech staff', 'Cleaning staff', 'Private service staff',
       'Cooking staff', 'Low-skill Laborers', 'Medicine staff',
       'Secretaries', 'Waiters/barmen staff', 'HR staff', 'Realty agents',
       'IT staff'], dtype=object)

In [7]:
# Variable de salida
# Note que el problema está mal balanceado, y en la aproximación
# ingenua se hace caso omiso de esto (es decir, se trata como un
# problema de clasificación binaria bien balanceado)

df["target"].value_counts()

target
0    8426
1    1283
Name: count, dtype: int64

In [8]:
# Proporciones de la variable de salida

df["target"].value_counts(normalize=True)

target
0    0.867855
1    0.132145
Name: proportion, dtype: float64

In [9]:
# Preparacion de la data

from sklearn.model_selection import train_test_split  #  type: ignore

X = df.drop(columns=["target"])
y = df["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=0,
)

In [10]:
# Modelo ingenuo
# Se entrena un modelo ingenuo que no toma en cuenta el desbalanceo
# de clases y no tiene en cuenta las caracteristicas de cada variable

from sklearn.compose import ColumnTransformer
from sklearn.compose import make_column_selector
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder


model = Pipeline(
    [
        (
            "transformer",
            ColumnTransformer(
                [
                    (
                        "onehot",
                        OrdinalEncoder(),
                        make_column_selector(dtype_include=object),
                    ),
                ],
                remainder="passthrough",
            ),
        ),
        (
            "rf",
            RandomForestClassifier(n_estimators=300, max_depth=12, min_samples_leaf=16),
        ),
    ]
)


model.fit(X_train, y_train)

Pipeline(steps=[('transformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehot', OrdinalEncoder(),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x1536d4a00>)])),
                ('rf',
                 RandomForestClassifier(max_depth=12, min_samples_leaf=16,
                                        n_estimators=300))])

In [11]:
y_train_predict = model.predict(X_train)
y_test_predict = model.predict(X_test)
print("Train Accuracy Score: {:.5}".format(accuracy_score(y_train, y_train_predict)))
print(" Test Accuracy Score: {:.5}".format(accuracy_score(y_test, y_test_predict)))

Train Accuracy Score: 0.86713
 Test Accuracy Score: 0.87075

In [12]:
# Matriz de confusion para el conjunto de entrenamiento

from sklearn.metrics import confusion_matrix


pd.DataFrame(
    data=confusion_matrix(y_train, model.predict(X_train)),
    index=["True 0", "True 1"],
    columns=["Predicted 0", "Predicted 1"],
)

        Predicted 0  Predicted 1
True 0         6735            0
True 1         1032            0

In [13]:
# Matriz de confusion para el conjunto de testing

pd.DataFrame(
    data=confusion_matrix(y_test, model.predict(X_test)),
    index=["True 0", "True 1"],
    columns=["Predicted 0", "Predicted 1"],
)

        Predicted 0  Predicted 1
True 0         1691            0
True 1          251            0